apiVersion: v1
kind: Pod
metadata:
  name: test-traffic-pod
  namespace: default
  labels:
    app: test-traffic
spec:
  containers:
    - name: traffic-generator
      image: busybox:latest
      command:
        - /bin/sh
        - -c
        - |
          echo "Starting traffic generation for 5 seconds..."
          timeout 5s ping -c 100 8.8.8.8 || true
          echo "Traffic generation complete. Keeping pod alive for verification..."
          sleep 3600
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
