apiVersion: v1
kind: Pod
metadata:
  name: test-traffic-pod
  namespace: default
  labels:
    app: test-traffic
spec:
  containers:
    - name: traffic-generator
      image: busybox:latest
      command:
        - /bin/sh
        - -c
        - |
          echo "Starting continuous traffic generation..."
          while true; do ping -c 1 8.8.8.8 || true; sleep 1; done
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
