apiVersion: v1
kind: Namespace
metadata:
  name: antrea-capture
  labels:
    app: antrea-capture

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: antrea-capture
  namespace: antrea-capture
spec:
  selector:
    matchLabels:
      app: antrea-capture
  template:
    metadata:
      labels:
        app: antrea-capture
    spec:
      serviceAccountName: antrea-capture
      hostPID: true
      containers:
        - name: antrea-capture
          image: antrea-capture:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: host-proc
              mountPath: /host/proc
              readOnly: true
      volumes:
        - name: host-proc
          hostPath:
            path: /proc
      tolerations:
        - operator: Exists
